[
vegetable {
  dataValues:
   { id: 1,
     name: 'carrot',
     color: 'orange',
     planted_on: 2018-08-06T23:49:28.952Z,
     updatedAt: 2018-08-06T23:49:29.058Z,
     createdAt: 2018-08-06T23:49:29.058Z },
  _previousDataValues:
   { name: 'carrot',
     color: 'orange',
     planted_on: 2018-08-06T23:49:28.952Z,
     id: 1,
     createdAt: 2018-08-06T23:49:29.058Z,
     updatedAt: 2018-08-06T23:49:29.058Z },
  _changed:
   { name: false,
     color: false,
     planted_on: false,
     id: false,
     createdAt: false,
     updatedAt: false },
  _modelOptions:
   { timestamps: true,
     validate: {},
     freezeTableName: false,
     underscored: false,
     underscoredAll: false,
     paranoid: false,
     rejectOnEmpty: false,
     whereCollection: null,
     schema: null,
     schemaDelimiter: '',
     defaultScope: {},
     scopes: [],
     indexes: [],
     name: [Object],
     omitNull: false,
     sequelize: [Sequelize],
     hooks: {},
     uniqueKeys: {} },
  _options: { isNewRecord: true, _schema: null, _schemaDelimiter: '' },
  __eagerlyLoadedAssociations: [],
  isNewRecord: false },
vegetable {
  dataValues:
   { id: 2,
     name: 'potato',
     color: 'brown',
     planted_on: 2018-08-06T23:49:28.953Z,
     updatedAt: 2018-08-06T23:49:29.059Z,
     createdAt: 2018-08-06T23:49:29.059Z },
  _previousDataValues:
   { name: 'potato',
     color: 'brown',
     planted_on: 2018-08-06T23:49:28.953Z,
     id: 2,
     createdAt: 2018-08-06T23:49:29.059Z,
     updatedAt: 2018-08-06T23:49:29.059Z },
  _changed:
   { name: false,
     color: false,
     planted_on: false,
     id: false,
     createdAt: false,
     updatedAt: false },
  _modelOptions:
   { timestamps: true,
     validate: {},
     freezeTableName: false,
     underscored: false,
     underscoredAll: false,
     paranoid: false,
     rejectOnEmpty: false,
     whereCollection: null,
     schema: null,
     schemaDelimiter: '',
     defaultScope: {},
     scopes: [],
     indexes: [],
     name: [Object],
     omitNull: false,
     sequelize: [Sequelize],
     hooks: {},
     uniqueKeys: {} },
  _options: { isNewRecord: true, _schema: null, _schemaDelimiter: '' },
  __eagerlyLoadedAssociations: [],
  isNewRecord: false }
]
